#!/usr/bin/perl
BEGIN {
	(my $srcdir = $0) =~ s,/[^/]+$,/,;
	unshift @INC, $srcdir;
}

use strict;
use warnings;
use Test::More tests => 529;
use test;

my @tests = (
        {
                status => OK,
                pdlist => 'test1/pdlist.out',
                pdinit => 'test1/pdinit.out',
                pdrebuild => 'test1/pdrebuild.out',
                ldinfo => 'test1/ldinfo.out',
                ldinit => 'test1/ldinit.out',
                batterywarning => 'test1/batterywarning.out',
                battery => 'test1/battery.out',
                cachevault => 'test1/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=43;;;; Battery0_V=3890;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (43 C)",
                        " - Voltage: OK (3890 mV)",
                ],
                c => 'test1',
        },
        {
                status => CRITICAL,
                pdlist => 'test2/pdlist.out',
                pdinit => 'test2/pdinit.out',
                pdrebuild => 'test2/pdrebuild.out',
                ldinfo => 'test2/ldinfo.out',
                ldinit => 'test2/ldinit.out',
                batterywarning => 'test2/batterywarning.out',
                battery => 'test2/battery.out',
                cachevault => 'test2/cachevault.out',
                message => 'Volumes(0): ; Devices(0): ',
                perfdata => '',
                longoutput => [],
                c => 'test2',
        },
        {
                status => OK,
                pdlist => 'test3/pdlist.out',
                pdinit => 'test3/pdinit.out',
                pdrebuild => 'test3/pdrebuild.out',
                ldinfo => 'test3/ldinfo.out',
                ldinit => 'test3/ldinit.out',
                batterywarning => 'test3/batterywarning.out',
                battery => 'test3/battery.out',
                cachevault => 'test3/cachevault.out',
                message => 'Volumes(1): RAID10:Optl; Devices(8): /c0/e8/s0,/c0/e8/s1,/c0/e8/s2,/c0/e8/s3,/c0/e8/s5,/c0/e8/s6,/c0/e8/s7,/c0/e8/s8=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=25;;;; Battery0_V=229;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (25 C)",
                        " - Voltage: OK (229 mV)",
                ],
                c => 'test3',
        },
        {
                status => OK,
                pdlist => 'test10/pdlist.out',
                pdinit => 'test10/pdinit.out',
                pdrebuild => 'test10/pdrebuild.out',
                ldinfo => 'test10/ldinfo.out',
                ldinit => 'test10/ldinit.out',
                batterywarning => 'test10/batterywarning.out',
                battery => 'test10/battery.out',
                cachevault => 'test10/cachevault.out',
                message => 'Volumes(2): /c0/v0:Optl,Virtual Disk 1:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=26;;;; Battery0_V=3901;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (26 C)",
                        " - Voltage: OK (3901 mV)",
                ],
                c => 'test10',
        },
        {
                status => OK,
                pdlist => 'test12/pdlist.out',
                pdinit => 'test12/pdinit.out',
                pdrebuild => 'test12/pdrebuild.out',
                ldinfo => 'test12/ldinfo.out',
                ldinit => 'test12/ldinit.out',
                batterywarning => 'test12/batterywarning.out',
                battery => 'test12/battery.out',
                cachevault => 'test12/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(8): /c0/e0/s0,/c0/e0/s1,/c0/e0/s2,/c0/e0/s3,/c0/e0/s4,/c0/e0/s5,/c0/e0/s6,/c0/e0/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=26;;;; Battery0_V=231;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (26 C)",
                        " - Voltage: OK (231 mV)",
                ],
                c => 'test12',
        },
        {
                status => OK,
                pdlist => 'test22/pdlist.out',
                pdinit => 'test22/pdinit.out',
                pdrebuild => 'test22/pdrebuild.out',
                ldinfo => 'test22/ldinfo.out',
                ldinit => 'test22/ldinit.out',
                batterywarning => 'test22/batterywarning.out',
                battery => 'test22/battery.out',
                cachevault => 'test22/cachevault.out',
                message => 'Volumes(1): RAID10:Optl; Devices(9): /c0/e0/s8=DHS /c0/e0/s0,/c0/e0/s1,/c0/e0/s2,/c0/e0/s3,/c0/e0/s4,/c0/e0/s5,/c0/e0/s6,/c0/e0/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=24;;;; Battery0_V=226;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (24 C)",
                        " - Voltage: OK (226 mV)",
                ],
                c => 'test22',
        },
        {
                status => OK,
                pdlist => 'test24/pdlist.out',
                pdinit => 'test24/pdinit.out',
                pdrebuild => 'test24/pdrebuild.out',
                ldinfo => 'test24/ldinfo.out',
                ldinit => 'test24/ldinit.out',
                batterywarning => 'test24/batterywarning.out',
                battery => 'test24/battery.out',
                cachevault => 'test24/cachevault.out',
                message => 'Volumes(2): /c0/v0:Optl,/c0/v1:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=28;;;; Battery0_V=3925;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (28 C)",
                        " - Voltage: OK (3925 mV)",
                ],
                c => 'test24',
        },
        {
                status => OK,
                pdlist => 'test29/pdlist.out',
                pdinit => 'test29/pdinit.out',
                pdrebuild => 'test29/pdrebuild.out',
                ldinfo => 'test29/ldinfo.out',
                ldinit => 'test29/ldinit.out',
                batterywarning => 'test29/batterywarning.out',
                battery => 'test29/battery.out',
                cachevault => 'test29/cachevault.out',
                message => 'Volumes(2): /c0/v0:Optl,/c0/v1:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=57;;;; Battery0_V=3935;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (57 C)",
                        " - Voltage: OK (3935 mV)",
                ],
                c => 'test29',
        },
        {
                status => OK,
                pdlist => 'test33/pdlist.out',
                pdinit => 'test33/pdinit.out',
                pdrebuild => 'test33/pdrebuild.out',
                ldinfo => 'test33/ldinfo.out',
                ldinit => 'test33/ldinit.out',
                batterywarning => 'test33/batterywarning.out',
                battery => 'test33/battery.out',
                cachevault => 'test33/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(8): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3,/c0/e252/s4,/c0/e252/s5,/c0/e252/s6,/c0/e252/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=20;;;; Battery0_V=233;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (20 C)",
                        " - Voltage: OK (233 mV)",
                ],
                c => 'test33',
        },
        {
                status => OK,
                pdlist => 'test40/pdlist.out',
                pdinit => 'test40/pdinit.out',
                pdrebuild => 'test40/pdrebuild.out',
                ldinfo => 'test40/ldinfo.out',
                ldinit => 'test40/ldinit.out',
                batterywarning => 'test40/batterywarning.out',
                battery => 'test40/battery.out',
                cachevault => 'test40/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(10): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7,/c0/e32/s8,/c0/e32/s9=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=50;;;; Battery0_V=3893;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (50 C)",
                        " - Voltage: OK (3893 mV)",
                ],
                c => 'test40',
        },
        {
                status => OK,
                pdlist => 'test45/pdlist.out',
                pdinit => 'test45/pdinit.out',
                pdrebuild => 'test45/pdrebuild.out',
                ldinfo => 'test45/ldinfo.out',
                ldinit => 'test45/ldinit.out',
                batterywarning => 'test45/batterywarning.out',
                battery => 'test45/battery.out',
                cachevault => 'test45/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(6): /c0/e32/s0,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=40;;;; Battery0_V=3926;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (40 C)",
                        " - Voltage: OK (3926 mV)",
                ],
                c => 'test45',
        },
        {
                status => OK,
                pdlist => 'test54/pdlist.out',
                pdinit => 'test54/pdinit.out',
                pdrebuild => 'test54/pdrebuild.out',
                ldinfo => 'test54/ldinfo.out',
                ldinit => 'test54/ldinit.out',
                batterywarning => 'test54/batterywarning.out',
                battery => 'test54/battery.out',
                cachevault => 'test54/cachevault.out',
                message => 'Volumes(1): /c0/v1:Optl; Devices(4): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test54',
        },
        {
                status => OK,
                pdlist => 'test55/pdlist.out',
                pdinit => 'test55/pdinit.out',
                pdrebuild => 'test55/pdrebuild.out',
                ldinfo => 'test55/ldinfo.out',
                ldinit => 'test55/ldinit.out',
                batterywarning => 'test55/batterywarning.out',
                battery => 'test55/battery.out',
                cachevault => 'test55/cachevault.out',
                message => 'Volumes(1): RAID10:Optl; Devices(8): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3,/c0/e252/s4,/c0/e252/s5,/c0/e252/s6,/c0/e252/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=37;;;; Battery0_V=239;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (37 C)",
                        " - Voltage: OK (239 mV)",
                ],
                c => 'test55',
        },
        {
                status => OK,
                pdlist => 'test58/pdlist.out',
                pdinit => 'test58/pdinit.out',
                pdrebuild => 'test58/pdrebuild.out',
                ldinfo => 'test58/ldinfo.out',
                ldinit => 'test58/ldinit.out',
                batterywarning => 'test58/batterywarning.out',
                battery => 'test58/battery.out',
                cachevault => 'test58/cachevault.out',
                message => 'Volumes(1): RAID10:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=30;;;; Battery0_V=3866;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (30 C)",
                        " - Voltage: OK (3866 mV)",
                ],
                c => 'test58',
        },
        {
                status => WARNING,
                pdlist => 'test62/pdlist.out',
                pdinit => 'test62/pdinit.out',
                pdrebuild => 'test62/pdrebuild.out',
                ldinfo => 'test62/ldinfo.out',
                ldinit => 'test62/ldinit.out',
                batterywarning => 'test62/batterywarning.out',
                battery => 'test62/battery.out',
                cachevault => 'test62/cachevault.out',
                message => 'Volumes(2): /c0/v238:Optl,WriteCache:DISABLED,/c0/v239:Optl,WriteCache:DISABLED; Devices(4): /c0/e252/s0,/c0/e252/s12,/c0/e252/s4,/c0/e252/s8=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test62',
        },
        {
                status => OK,
                pdlist => 'test69/pdlist.out',
                pdinit => 'test69/pdinit.out',
                pdrebuild => 'test69/pdrebuild.out',
                ldinfo => 'test69/ldinfo.out',
                ldinit => 'test69/ldinit.out',
                batterywarning => 'test69/batterywarning.out',
                battery => 'test69/battery.out',
                cachevault => 'test69/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=33;;;; Battery0_V=3895;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (33 C)",
                        " - Voltage: OK (3895 mV)",
                ],
                c => 'test69',
        },
        {
                status => OK,
                pdlist => 'test72/pdlist.out',
                pdinit => 'test72/pdinit.out',
                pdrebuild => 'test72/pdrebuild.out',
                ldinfo => 'test72/ldinfo.out',
                ldinit => 'test72/ldinit.out',
                batterywarning => 'test72/batterywarning.out',
                battery => 'test72/battery.out',
                cachevault => 'test72/cachevault.out',
                message => 'Volumes(1): RAID10:Optl,WriteCache:DISABLED; Devices(4): /c0/e62/s0,/c0/e62/s1,/c0/e62/s2,/c0/e62/s3=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test72',
        },
        {
                status => OK,
                pdlist => 'test73/pdlist.out',
                pdinit => 'test73/pdinit.out',
                pdrebuild => 'test73/pdrebuild.out',
                ldinfo => 'test73/ldinfo.out',
                ldinit => 'test73/ldinit.out',
                batterywarning => 'test73/batterywarning.out',
                battery => 'test73/battery.out',
                cachevault => 'test73/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(6): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3,/c0/e252/s4,/c0/e252/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=30;;;; Battery0_V=3948;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (30 C)",
                        " - Voltage: OK (3948 mV)",
                ],
                c => 'test73',
        },
        {
                status => WARNING,
                pdlist => 'test77/pdlist.out',
                pdinit => 'test77/pdinit.out',
                pdrebuild => 'test77/pdrebuild.out',
                ldinfo => 'test77/ldinfo.out',
                ldinit => 'test77/ldinit.out',
                batterywarning => 'test77/batterywarning.out',
                battery => 'test77/battery.out',
                cachevault => 'test77/cachevault.out',
                message => 'Volumes(2): /c0/v238:Optl,WriteCache:DISABLED,/c0/v239:Optl,WriteCache:DISABLED; Devices(3): /c0/e252/s12,/c0/e252/s4,/c0/e252/s8=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test77',
        },
        {
                status => CRITICAL,
                pdlist => 'test78/pdlist.out',
                pdinit => 'test78/pdinit.out',
                pdrebuild => 'test78/pdrebuild.out',
                ldinfo => 'test78/ldinfo.out',
                ldinit => 'test78/ldinit.out',
                batterywarning => 'test78/batterywarning.out',
                battery => 'test78/battery.out',
                cachevault => 'test78/cachevault.out',
                message => 'Volumes(1): /c0/v0:Dgrd; Devices(5): /c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=53;;;; Battery0_V=3905;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (53 C)",
                        " - Voltage: OK (3905 mV)",
                ],
                c => 'test78',
        },
        {
                status => OK,
                pdlist => 'test81/pdlist.out',
                pdinit => 'test81/pdinit.out',
                pdrebuild => 'test81/pdrebuild.out',
                ldinfo => 'test81/ldinfo.out',
                ldinit => 'test81/ldinit.out',
                batterywarning => 'test81/batterywarning.out',
                battery => 'test81/battery.out',
                cachevault => 'test81/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(8): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3,/c0/e252/s4,/c0/e252/s5,/c0/e252/s6,/c0/e252/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=22;;;; Battery0_V=3987;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (22 C)",
                        " - Voltage: OK (3987 mV)",
                ],
                c => 'test81',
        },
        {
                status => OK,
                pdlist => 'test83/pdlist.out',
                pdinit => 'test83/pdinit.out',
                pdrebuild => 'test83/pdrebuild.out',
                ldinfo => 'test83/ldinfo.out',
                ldinit => 'test83/ldinit.out',
                batterywarning => 'test83/batterywarning.out',
                battery => 'test83/battery.out',
                cachevault => 'test83/cachevault.out',
                message => 'Volumes(2): RAID10:Optl,RAID5:Optl; Devices(14): /c0/e32/s0,/c0/e32/s1,/c0/e32/s10,/c0/e32/s11,/c0/e32/s12,/c0/e32/s13,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7,/c0/e32/s8,/c0/e32/s9=Onln; Batteries(2): 0,1=Optimal',
                perfdata => 'Battery0_T=45;;;; Battery0_V=3926;;;;\nBattery1_T=32;;;; Battery1_V=3895;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (45 C)",
                        " - Voltage: OK (3926 mV)\\nBattery1:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (32 C)",
                        " - Voltage: OK (3895 mV)",
                ],
                c => 'test83',
        },
        {
                status => OK,
                pdlist => 'test85/pdlist.out',
                pdinit => 'test85/pdinit.out',
                pdrebuild => 'test85/pdrebuild.out',
                ldinfo => 'test85/ldinfo.out',
                ldinit => 'test85/ldinit.out',
                batterywarning => 'test85/batterywarning.out',
                battery => 'test85/battery.out',
                cachevault => 'test85/cachevault.out',
                message => 'Volumes(1): raid10:Optl; Devices(4): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=27;;;; Battery0_V=239;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (27 C)",
                        " - Voltage: OK (239 mV)",
                ],
                c => 'test85',
        },
        {
                status => CRITICAL,
                pdlist => 'test89/pdlist.out',
                pdinit => 'test89/pdinit.out',
                pdrebuild => 'test89/pdrebuild.out',
                ldinfo => 'test89/ldinfo.out',
                ldinit => 'test89/ldinit.out',
                batterywarning => 'test89/batterywarning.out',
                battery => 'test89/battery.out',
                cachevault => 'test89/cachevault.out',
                message => 'Volumes(2): /c0/v238:Optl,WriteCache:DISABLED,/c0/v239:Optl,WriteCache:DISABLED; Devices(3): /c0/e252/s12,/c0/e252/s4,/c0/e252/s8=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test89',
        },
        {
                status => OK,
                pdlist => 'test91/pdlist.out',
                pdinit => 'test91/pdinit.out',
                pdrebuild => 'test91/pdrebuild.out',
                ldinfo => 'test91/ldinfo.out',
                ldinit => 'test91/ldinit.out',
                batterywarning => 'test91/batterywarning.out',
                battery => 'test91/battery.out',
                cachevault => 'test91/cachevault.out',
                message => 'Volumes(1): RAID10:Optl,WriteCache:DISABLED; Devices(6): /c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test91',
        },
        {
                status => OK,
                pdlist => 'test92/pdlist.out',
                pdinit => 'test92/pdinit.out',
                pdrebuild => 'test92/pdrebuild.out',
                ldinfo => 'test92/ldinfo.out',
                ldinit => 'test92/ldinit.out',
                batterywarning => 'test92/batterywarning.out',
                battery => 'test92/battery.out',
                cachevault => 'test92/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=30;;;; Battery0_V=3899;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (30 C)",
                        " - Voltage: OK (3899 mV)",
                ],
                c => 'test92',
        },
        {
                status => OK,
                pdlist => 'test94/pdlist.out',
                pdinit => 'test94/pdinit.out',
                pdrebuild => 'test94/pdrebuild.out',
                ldinfo => 'test94/ldinfo.out',
                ldinit => 'test94/ldinit.out',
                batterywarning => 'test94/batterywarning.out',
                battery => 'test94/battery.out',
                cachevault => 'test94/cachevault.out',
                message => 'Volumes(1): RAID10:Optl,WriteCache:DISABLED; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test94',
        },
        {
                status => OK,
                pdlist => 'test97/pdlist.out',
                pdinit => 'test97/pdinit.out',
                pdrebuild => 'test97/pdrebuild.out',
                ldinfo => 'test97/ldinfo.out',
                ldinit => 'test97/ldinit.out',
                batterywarning => 'test97/batterywarning.out',
                battery => 'test97/battery.out',
                cachevault => 'test97/cachevault.out',
                message => 'Volumes(2): /c0/v0:Optl,/c0/v1:Optl; Devices(8): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3,/c0/e252/s4,/c0/e252/s5,/c0/e252/s6,/c0/e252/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=48;;;; Battery0_V=3905;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (48 C)",
                        " - Voltage: OK (3905 mV)",
                ],
                c => 'test97',
        },
        {
                status => OK,
                pdlist => 'test100/pdlist.out',
                pdinit => 'test100/pdinit.out',
                pdrebuild => 'test100/pdrebuild.out',
                ldinfo => 'test100/ldinfo.out',
                ldinit => 'test100/ldinit.out',
                batterywarning => 'test100/batterywarning.out',
                battery => 'test100/battery.out',
                cachevault => 'test100/cachevault.out',
                message => 'Volumes(2): /c0/v0:Optl,/c0/v1:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=46;;;; Battery0_V=3900;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (46 C)",
                        " - Voltage: OK (3900 mV)",
                ],
                c => 'test100',
        },
        {
                status => OK,
                pdlist => 'test101/pdlist.out',
                pdinit => 'test101/pdinit.out',
                pdrebuild => 'test101/pdrebuild.out',
                ldinfo => 'test101/ldinfo.out',
                ldinit => 'test101/ldinit.out',
                batterywarning => 'test101/batterywarning.out',
                battery => 'test101/battery.out',
                cachevault => 'test101/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl,WriteCache:DISABLED; Devices(4): /c0/e62/s0,/c0/e62/s1,/c0/e62/s2,/c0/e62/s3=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test101',
        },
        {
                status => OK,
                pdlist => 'test102/pdlist.out',
                pdinit => 'test102/pdinit.out',
                pdrebuild => 'test102/pdrebuild.out',
                ldinfo => 'test102/ldinfo.out',
                ldinit => 'test102/ldinit.out',
                batterywarning => 'test102/batterywarning.out',
                battery => 'test102/battery.out',
                cachevault => 'test102/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl,WriteCache:DISABLED; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test102',
        },
        {
                status => OK,
                pdlist => 'test103/pdlist.out',
                pdinit => 'test103/pdinit.out',
                pdrebuild => 'test103/pdrebuild.out',
                ldinfo => 'test103/ldinfo.out',
                ldinit => 'test103/ldinit.out',
                batterywarning => 'test103/batterywarning.out',
                battery => 'test103/battery.out',
                cachevault => 'test103/cachevault.out',
                message => 'Volumes(2): Virtual Disk 0:Optl,WriteCache:DISABLED,Virtual Disk 1:Optl,WriteCache:DISABLED; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test103',
        },
        {
                status => OK,
                pdlist => 'test104/pdlist.out',
                pdinit => 'test104/pdinit.out',
                pdrebuild => 'test104/pdrebuild.out',
                ldinfo => 'test104/ldinfo.out',
                ldinit => 'test104/ldinit.out',
                batterywarning => 'test104/batterywarning.out',
                battery => 'test104/battery.out',
                cachevault => 'test104/cachevault.out',
                message => 'Volumes(2): /c0/v0:Optl,/c0/v1:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=31;;;; Battery0_V=3905;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (31 C)",
                        " - Voltage: OK (3905 mV)",
                ],
                c => 'test104',
        },
        {
                status => OK,
                pdlist => 'test105/pdlist.out',
                pdinit => 'test105/pdinit.out',
                pdrebuild => 'test105/pdrebuild.out',
                ldinfo => 'test105/ldinfo.out',
                ldinit => 'test105/ldinit.out',
                batterywarning => 'test105/batterywarning.out',
                battery => 'test105/battery.out',
                cachevault => 'test105/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=40;;;; Battery0_V=3896;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (40 C)",
                        " - Voltage: OK (3896 mV)",
                ],
                c => 'test105',
        },
        {
                status => OK,
                pdlist => 'test107/pdlist.out',
                pdinit => 'test107/pdinit.out',
                pdrebuild => 'test107/pdrebuild.out',
                ldinfo => 'test107/ldinfo.out',
                ldinit => 'test107/ldinit.out',
                batterywarning => 'test107/batterywarning.out',
                battery => 'test107/battery.out',
                cachevault => 'test107/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(8): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3,/c0/e252/s4,/c0/e252/s5,/c0/e252/s6,/c0/e252/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=22;;;; Battery0_V=3974;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (22 C)",
                        " - Voltage: OK (3974 mV)",
                ],
                c => 'test107',
        },
        {
                status => OK,
                pdlist => 'test109/pdlist.out',
                pdinit => 'test109/pdinit.out',
                pdrebuild => 'test109/pdrebuild.out',
                ldinfo => 'test109/ldinfo.out',
                ldinit => 'test109/ldinit.out',
                batterywarning => 'test109/batterywarning.out',
                battery => 'test109/battery.out',
                cachevault => 'test109/cachevault.out',
                message => 'Volumes(1): Virtual Disk 0:Optl; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=46;;;; Battery0_V=3935;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (46 C)",
                        " - Voltage: OK (3935 mV)",
                ],
                c => 'test109',
        },
        {
                status => OK,
                pdlist => 'test110/pdlist.out',
                pdinit => 'test110/pdinit.out',
                pdrebuild => 'test110/pdrebuild.out',
                ldinfo => 'test110/ldinfo.out',
                ldinit => 'test110/ldinit.out',
                batterywarning => 'test110/batterywarning.out',
                battery => 'test110/battery.out',
                cachevault => 'test110/cachevault.out',
                message => 'Volumes(3): /c0/v0:Optl,/c0/v1:Optl,/c0/v2:Optl; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=50;;;; Battery0_V=3879;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (50 C)",
                        " - Voltage: OK (3879 mV)",
                ],
                c => 'test110',
        },
        {
                status => OK,
                pdlist => 'test112/pdlist.out',
                pdinit => 'test112/pdinit.out',
                pdrebuild => 'test112/pdrebuild.out',
                ldinfo => 'test112/ldinfo.out',
                ldinit => 'test112/ldinit.out',
                batterywarning => 'test112/batterywarning.out',
                battery => 'test112/battery.out',
                cachevault => 'test112/cachevault.out',
                message => 'Volumes(3): /c0/v0:Optl,/c0/v1:Optl,Virtual Disk 2:Optl; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=55;;;; Battery0_V=3873;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (55 C)",
                        " - Voltage: OK (3873 mV)",
                ],
                c => 'test112',
        },
        {
                status => CRITICAL,
                pdlist => 'test117/pdlist.out',
                pdinit => 'test117/pdinit.out',
                pdrebuild => 'test117/pdrebuild.out',
                ldinfo => 'test117/ldinfo.out',
                ldinit => 'test117/ldinit.out',
                batterywarning => 'test117/batterywarning.out',
                battery => 'test117/battery.out',
                cachevault => 'test117/cachevault.out',
                message => 'Volumes(1): RAID10:Optl,WriteCache:DISABLED; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Learning',
                perfdata => 'Battery0_T=56;;;; Battery0_V=3427;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Learning",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (56 C)",
                        " - Voltage: OK (3427 mV)",
                ],
                c => 'test117',
        },
        {
                status => OK,
                pdlist => 'test118/pdlist.out',
                pdinit => 'test118/pdinit.out',
                pdrebuild => 'test118/pdrebuild.out',
                ldinfo => 'test118/ldinfo.out',
                ldinit => 'test118/ldinit.out',
                batterywarning => 'test118/batterywarning.out',
                battery => 'test118/battery.out',
                cachevault => 'test118/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=49;;;; Battery0_V=3901;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (49 C)",
                        " - Voltage: OK (3901 mV)",
                ],
                c => 'test118',
        },
        {
                status => OK,
                pdlist => 'test119/pdlist.out',
                pdinit => 'test119/pdinit.out',
                pdrebuild => 'test119/pdrebuild.out',
                ldinfo => 'test119/ldinfo.out',
                ldinit => 'test119/ldinit.out',
                batterywarning => 'test119/batterywarning.out',
                battery => 'test119/battery.out',
                cachevault => 'test119/cachevault.out',
                message => 'Volumes(1): RAID10:Optl; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=53;;;; Battery0_V=3909;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (53 C)",
                        " - Voltage: OK (3909 mV)",
                ],
                c => 'test119',
        },
        {
                status => OK,
                pdlist => 'test120/pdlist.out',
                pdinit => 'test120/pdinit.out',
                pdrebuild => 'test120/pdrebuild.out',
                ldinfo => 'test120/ldinfo.out',
                ldinit => 'test120/ldinit.out',
                batterywarning => 'test120/batterywarning.out',
                battery => 'test120/battery.out',
                cachevault => 'test120/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl,WriteCache:DISABLED; Devices(4): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=42;;;; Battery0_V=3905;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (42 C)",
                        " - Voltage: OK (3905 mV)",
                ],
                c => 'test120',
        },
        {
                status => OK,
                pdlist => 'test121/pdlist.out',
                pdinit => 'test121/pdinit.out',
                pdrebuild => 'test121/pdrebuild.out',
                ldinfo => 'test121/ldinfo.out',
                ldinit => 'test121/ldinit.out',
                batterywarning => 'test121/batterywarning.out',
                battery => 'test121/battery.out',
                cachevault => 'test121/cachevault.out',
                message => 'Volumes(1): RAID10:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=59;;;; Battery0_V=3870;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (59 C)",
                        " - Voltage: OK (3870 mV)",
                ],
                c => 'test121',
        },
        {
                status => OK,
                pdlist => 'test123/pdlist.out',
                pdinit => 'test123/pdinit.out',
                pdrebuild => 'test123/pdrebuild.out',
                ldinfo => 'test123/ldinfo.out',
                ldinit => 'test123/ldinit.out',
                batterywarning => 'test123/batterywarning.out',
                battery => 'test123/battery.out',
                cachevault => 'test123/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=55;;;; Battery0_V=3893;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (55 C)",
                        " - Voltage: OK (3893 mV)",
                ],
                c => 'test123',
        },
        {
                status => OK,
                pdlist => 'test125/pdlist.out',
                pdinit => 'test125/pdinit.out',
                pdrebuild => 'test125/pdrebuild.out',
                ldinfo => 'test125/ldinfo.out',
                ldinit => 'test125/ldinit.out',
                batterywarning => 'test125/batterywarning.out',
                battery => 'test125/battery.out',
                cachevault => 'test125/cachevault.out',
                message => 'Volumes(1): Virtual Disk 0:Optl; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=33;;;; Battery0_V=3868;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (33 C)",
                        " - Voltage: OK (3868 mV)",
                ],
                c => 'test125',
        },
        {
                status => OK,
                pdlist => 'test131/pdlist.out',
                pdinit => 'test131/pdinit.out',
                pdrebuild => 'test131/pdrebuild.out',
                ldinfo => 'test131/ldinfo.out',
                ldinit => 'test131/ldinit.out',
                batterywarning => 'test131/batterywarning.out',
                battery => 'test131/battery.out',
                cachevault => 'test131/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(4): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=38;;;; Battery0_V=4017;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (38 C)",
                        " - Voltage: OK (4017 mV)",
                ],
                c => 'test131',
        },
        {
                status => OK,
                pdlist => 'test133/pdlist.out',
                pdinit => 'test133/pdinit.out',
                pdrebuild => 'test133/pdrebuild.out',
                ldinfo => 'test133/ldinfo.out',
                ldinit => 'test133/ldinit.out',
                batterywarning => 'test133/batterywarning.out',
                battery => 'test133/battery.out',
                cachevault => 'test133/cachevault.out',
                message => 'Volumes(2): Virtual Disk 0:Optl,vd1:Optl; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=45;;;; Battery0_V=3874;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (45 C)",
                        " - Voltage: OK (3874 mV)",
                ],
                c => 'test133',
        },
        {
                status => OK,
                pdlist => 'test139/pdlist.out',
                pdinit => 'test139/pdinit.out',
                pdrebuild => 'test139/pdrebuild.out',
                ldinfo => 'test139/ldinfo.out',
                ldinit => 'test139/ldinit.out',
                batterywarning => 'test139/batterywarning.out',
                battery => 'test139/battery.out',
                cachevault => 'test139/cachevault.out',
                message => 'Volumes(0): ; Devices(26): /c0/e27/s0,/c0/e27/s1,/c0/e27/s10,/c0/e27/s11,/c0/e27/s12,/c0/e27/s13,/c0/e27/s14,/c0/e27/s15,/c0/e27/s16,/c0/e27/s17,/c0/e27/s18,/c0/e27/s19,/c0/e27/s2,/c0/e27/s20,/c0/e27/s21,/c0/e27/s22,/c0/e27/s23,/c0/e27/s24,/c0/e27/s25,/c0/e27/s3,/c0/e27/s4,/c0/e27/s5,/c0/e27/s6,/c0/e27/s7,/c0/e27/s8,/c0/e27/s9=UGood; Batteries(1): 0=Un-supported command',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Un-supported command",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test139',
        },
        {
                status => OK,
                pdlist => 'test140/pdlist.out',
                pdinit => 'test140/pdinit.out',
                pdrebuild => 'test140/pdrebuild.out',
                ldinfo => 'test140/ldinfo.out',
                ldinit => 'test140/ldinit.out',
                batterywarning => 'test140/batterywarning.out',
                battery => 'test140/battery.out',
                cachevault => 'test140/cachevault.out',
                message => 'Volumes(1): Virtual Disk 0:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=56;;;; Battery0_V=3896;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (56 C)",
                        " - Voltage: OK (3896 mV)",
                ],
                c => 'test140',
        },
        {
                status => OK,
                pdlist => 'test141/pdlist.out',
                pdinit => 'test141/pdinit.out',
                pdrebuild => 'test141/pdrebuild.out',
                ldinfo => 'test141/ldinfo.out',
                ldinit => 'test141/ldinit.out',
                batterywarning => 'test141/batterywarning.out',
                battery => 'test141/battery.out',
                cachevault => 'test141/cachevault.out',
                message => 'Volumes(0): ; Devices(26): /c0/e26/s0,/c0/e26/s1,/c0/e26/s10,/c0/e26/s11,/c0/e26/s12,/c0/e26/s13,/c0/e26/s14,/c0/e26/s15,/c0/e26/s16,/c0/e26/s17,/c0/e26/s18,/c0/e26/s19,/c0/e26/s2,/c0/e26/s20,/c0/e26/s21,/c0/e26/s22,/c0/e26/s23,/c0/e26/s24,/c0/e26/s25,/c0/e26/s3,/c0/e26/s4,/c0/e26/s5,/c0/e26/s6,/c0/e26/s7,/c0/e26/s8,/c0/e26/s9=UGood; Batteries(1): 0=Un-supported command',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Un-supported command",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test141',
        },
        {
                status => OK,
                pdlist => 'test149/pdlist.out',
                pdinit => 'test149/pdinit.out',
                pdrebuild => 'test149/pdrebuild.out',
                ldinfo => 'test149/ldinfo.out',
                ldinit => 'test149/ldinit.out',
                batterywarning => 'test149/batterywarning.out',
                battery => 'test149/battery.out',
                cachevault => 'test149/cachevault.out',
                message => 'Volumes(1): RAID10:Optl; Devices(4): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=31;;;; Battery0_V=3918;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (31 C)",
                        " - Voltage: OK (3918 mV)",
                ],
                c => 'test149',
        },
        {
                status => OK,
                pdlist => 'test151/pdlist.out',
                pdinit => 'test151/pdinit.out',
                pdrebuild => 'test151/pdrebuild.out',
                ldinfo => 'test151/ldinfo.out',
                ldinit => 'test151/ldinit.out',
                batterywarning => 'test151/batterywarning.out',
                battery => 'test151/battery.out',
                cachevault => 'test151/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl,WriteCache:DISABLED; Devices(4): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test151',
        },
        {
                status => OK,
                pdlist => 'test152/pdlist.out',
                pdinit => 'test152/pdinit.out',
                pdrebuild => 'test152/pdrebuild.out',
                ldinfo => 'test152/ldinfo.out',
                ldinit => 'test152/ldinit.out',
                batterywarning => 'test152/batterywarning.out',
                battery => 'test152/battery.out',
                cachevault => 'test152/cachevault.out',
                message => 'Volumes(2): Virtual Disk 0:Optl,/c0/v1:Optl; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=53;;;; Battery0_V=3918;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (53 C)",
                        " - Voltage: OK (3918 mV)",
                ],
                c => 'test152',
        },
        {
                status => OK,
                pdlist => 'test154/pdlist.out',
                pdinit => 'test154/pdinit.out',
                pdrebuild => 'test154/pdrebuild.out',
                ldinfo => 'test154/ldinfo.out',
                ldinit => 'test154/ldinit.out',
                batterywarning => 'test154/batterywarning.out',
                battery => 'test154/battery.out',
                cachevault => 'test154/cachevault.out',
                message => 'Volumes(1): RAID10:Optl,WriteCache:DISABLED; Devices(6): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test154',
        },
        {
                status => OK,
                pdlist => 'test155/pdlist.out',
                pdinit => 'test155/pdinit.out',
                pdrebuild => 'test155/pdrebuild.out',
                ldinfo => 'test155/ldinfo.out',
                ldinit => 'test155/ldinit.out',
                batterywarning => 'test155/batterywarning.out',
                battery => 'test155/battery.out',
                cachevault => 'test155/cachevault.out',
                message => 'Volumes(0): ; Devices(0): ; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=40;;;; Battery0_V=3893;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (40 C)",
                        " - Voltage: OK (3893 mV)",
                ],
                c => 'test155',
        },
        {
                status => OK,
                pdlist => 'test156/pdlist.out',
                pdinit => 'test156/pdinit.out',
                pdrebuild => 'test156/pdrebuild.out',
                ldinfo => 'test156/ldinfo.out',
                ldinit => 'test156/ldinit.out',
                batterywarning => 'test156/batterywarning.out',
                battery => 'test156/battery.out',
                cachevault => 'test156/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=51;;;; Battery0_V=3908;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (51 C)",
                        " - Voltage: OK (3908 mV)",
                ],
                c => 'test156',
        },
        {
                status => OK,
                pdlist => 'test157/pdlist.out',
                pdinit => 'test157/pdinit.out',
                pdrebuild => 'test157/pdrebuild.out',
                ldinfo => 'test157/ldinfo.out',
                ldinit => 'test157/ldinit.out',
                batterywarning => 'test157/batterywarning.out',
                battery => 'test157/battery.out',
                cachevault => 'test157/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=40;;;; Battery0_V=3897;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (40 C)",
                        " - Voltage: OK (3897 mV)",
                ],
                c => 'test157',
        },
        {
                status => OK,
                pdlist => 'test167/pdlist.out',
                pdinit => 'test167/pdinit.out',
                pdrebuild => 'test167/pdrebuild.out',
                ldinfo => 'test167/ldinfo.out',
                ldinit => 'test167/ldinit.out',
                batterywarning => 'test167/batterywarning.out',
                battery => 'test167/battery.out',
                cachevault => 'test167/cachevault.out',
                message => 'Volumes(0): ; Devices(0): ; Batteries(1): 0=Un-supported command',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Un-supported command",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test167',
        },
        {
                status => OK,
                pdlist => 'test174/pdlist.out',
                pdinit => 'test174/pdinit.out',
                pdrebuild => 'test174/pdrebuild.out',
                ldinfo => 'test174/ldinfo.out',
                ldinit => 'test174/ldinit.out',
                batterywarning => 'test174/batterywarning.out',
                battery => 'test174/battery.out',
                cachevault => 'test174/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl,WriteCache:DISABLED; Devices(8): /c0/e32/s0,/c0/e32/s1,/c0/e32/s2,/c0/e32/s3,/c0/e32/s4,/c0/e32/s5,/c0/e32/s6,/c0/e32/s7=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test174',
        },
        {
                status => OK,
                pdlist => 'test185/pdlist.out',
                pdinit => 'test185/pdinit.out',
                pdrebuild => 'test185/pdrebuild.out',
                ldinfo => 'test185/ldinfo.out',
                ldinit => 'test185/ldinit.out',
                batterywarning => 'test185/batterywarning.out',
                battery => 'test185/battery.out',
                cachevault => 'test185/cachevault.out',
                message => 'Volumes(0): ; Devices(0): ; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: OFF",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test185',
        },
        {
                status => CRITICAL,
                pdlist => 'test187/pdlist.out',
                pdinit => 'test187/pdinit.out',
                pdrebuild => 'test187/pdrebuild.out',
                ldinfo => 'test187/ldinfo.out',
                ldinit => 'test187/ldinit.out',
                batterywarning => 'test187/batterywarning.out',
                battery => 'test187/battery.out',
                cachevault => 'test187/cachevault.out',
                message => 'Volumes(2): /c0/v238:Optl,WriteCache:DISABLED,/c0/v239:Optl,WriteCache:DISABLED; Devices(4): /c0/e252/s0,/c0/e252/s10,/c0/e252/s6,/c0/e252/s8=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test187',
        },
        {
                status => CRITICAL,
                pdlist => 'test191/pdlist.out',
                pdinit => 'test191/pdinit.out',
                pdrebuild => 'test191/pdrebuild.out',
                ldinfo => 'test191/ldinfo.out',
                ldinit => 'test191/ldinit.out',
                batterywarning => 'test191/batterywarning.out',
                battery => 'test191/battery.out',
                cachevault => 'test191/cachevault.out',
                message => 'Volumes(0): ; Devices(0): ; Batteries(1): 0=Failed',
                perfdata => 'Battery0_T=26;;;; Battery0_V=502;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Failed",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: OK (26 C)",
                        " - Voltage: OK (502 mV)",
                ],
                c => 'test191',
        },
        {
                status => CRITICAL,
                pdlist => 'test194/pdlist.out',
                pdinit => 'test194/pdinit.out',
                pdrebuild => 'test194/pdrebuild.out',
                ldinfo => 'test194/ldinfo.out',
                ldinit => 'test194/ldinit.out',
                batterywarning => 'test194/batterywarning.out',
                battery => 'test194/battery.out',
                cachevault => 'test194/cachevault.out',
                message => 'Volumes(1): /c0/v239:Optl,WriteCache:DISABLED; Devices(4): /c0/e252/s10,/c0/e252/s4,/c0/e252/s6,/c0/e252/s8=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test194',
        },
        {
                status => OK,
                pdlist => 'test197/pdlist.out',
                pdinit => 'test197/pdinit.out',
                pdrebuild => 'test197/pdrebuild.out',
                ldinfo => 'test197/ldinfo.out',
                ldinit => 'test197/ldinit.out',
                batterywarning => 'test197/batterywarning.out',
                battery => 'test197/battery.out',
                cachevault => 'test197/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(4): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=33;;;; Battery0_V=3942;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (33 C)",
                        " - Voltage: OK (3942 mV)",
                ],
                c => 'test197',
        },
        {
                status => CRITICAL,
                pdlist => 'test198/pdlist.out',
                pdinit => 'test198/pdinit.out',
                pdrebuild => 'test198/pdrebuild.out',
                ldinfo => 'test198/ldinfo.out',
                ldinit => 'test198/ldinit.out',
                batterywarning => 'test198/batterywarning.out',
                battery => 'test198/battery.out',
                cachevault => 'test198/cachevault.out',
                message => 'Volumes(1): /c0/v0:Optl; Devices(4): /c0/e252/s0,/c0/e252/s1,/c0/e252/s2,/c0/e252/s3=Onln; Batteries(1): 0=Cachevault is absent',
                perfdata => 'Battery0_T=0;;;; Battery0_V=0;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Cachevault is absent",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: Yes",
                        " - Replacement required: Yes",
                        " - About to fail: No",
                        " - Temperature: Unknown (0 C)",
                        " - Voltage: Unknown (0 mV)",
                ],
                c => 'test198',
        },
        {
                status => OK,
                pdlist => 'test199/pdlist.out',
                pdinit => 'test199/pdinit.out',
                pdrebuild => 'test199/pdrebuild.out',
                ldinfo => 'test199/ldinfo.out',
                ldinit => 'test199/ldinit.out',
                batterywarning => 'test199/batterywarning.out',
                battery => 'test199/battery.out',
                cachevault => 'test199/cachevault.out',
                message => 'Volumes(2): /c0/v0:Optl,/c0/v1:Optl; Devices(4): /c0/e252/s4,/c0/e252/s5,/c0/e252/s6,/c0/e252/s7=Onln; Batteries(1): 0=Optimal',
                perfdata => 'Battery0_T=29;;;; Battery0_V=231;;;;',
                longoutput => [
                        "Battery0:",
                        " - State: Optimal",
                        " - Battery Warning: ON",
                        " - Charging status: None",
                        " - Learn cycle requested: No",
                        " - Learn cycle active: No",
                        " - Missing: No",
                        " - Replacement required: No",
                        " - About to fail: No",
                        " - Temperature: OK (29 C)",
                        " - Voltage: OK (231 mV)",
                ],
                c => 'test199',
        },
);

# test that plugin can be created
ok(storcli->new, "plugin created");

foreach my $test (@tests) {
        my %options = (
                bbu_monitoring => 1,
#                cache_fail     => 0,
        );
#        $options{bbu_monitoring} = $test->{bbu} if exists $test->{bbu};

        if (defined($test->{bbulearn_status})) {
                $options{bbulearn_status} = $test->{bbulearn_status};
        }

	my $plugin = storcli->new(
		program => '/bin/true',
		commands => {
			'pdlist' => ['<', TESTDIR . '/data/storcli/' . $test->{pdlist} ],
			'pdinit' => ['<', TESTDIR . '/data/storcli/' . $test->{pdinit} ],
			'pdrebuild' => ['<', TESTDIR . '/data/storcli/' . $test->{pdrebuild} ],
			'ldinfo' => ['<', TESTDIR . '/data/storcli/' . $test->{ldinfo} ],
			'ldinit' => ['<', TESTDIR . '/data/storcli/' . $test->{ldinit} ],
			'batterywarning' => ['<', TESTDIR . '/data/storcli/' . $test->{batterywarning} ],
			'battery' => ['<', TESTDIR . '/data/storcli/' . $test->{battery} ],
			'cachevault' => ['<', TESTDIR . '/data/storcli/' . $test->{cachevault} ],
		},
                options => \%options,
	);
	ok($plugin, "plugin created: $test->{pdlist}");

	$plugin->check;
	ok(1, "check ran");

	ok(defined($plugin->status), "status code set");
	is($plugin->status, $test->{status}, "status code matches");
	is($plugin->message, $test->{message}, "status message");
        is($plugin->perfdata, $test->{perfdata}, "performance data");
        my $longoutput = join("\n", @{$test->{longoutput}});
        is($plugin->longoutput, $longoutput, "long output");

        my $c = $plugin->parse;
        my $df = './' . TESTDIR . '/dump/storcli/' . $test->{c};
        if (!-f $df) {
                store_dump $df, $c;
                # trigger error so that we don't have feeling all is ok ;)
                ok(0, "Created dump for $df");
        }
        my $dump = read_dump($df);
        is_deeply($c, $dump, "controller structure");
}
